name: salah_snap_version_second
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # android_alarm_manager_plus: ^5.0.0
  android_intent_plus: ^6.0.0
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  collection: ^1.19.1
  equatable: ^2.0.7
  flutter_animate: ^4.5.2
  flutter_cache_manager: 3.4.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.7
  font_awesome_flutter: ^10.12.0
  from_css_color: 2.0.0
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  google_mlkit_text_recognition: ^0.15.0
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_path: ^0.8.0
  mime_type: ^1.0.1
  page_transition: ^2.2.1
  # path_provider: ^2.1.5
  # path_provider_android: ^2.2.20
  # path_provider_foundation: ^2.4.3
  # path_provider_linux: 2.2.1
  # path_provider_platform_interface: 2.1.2
  # path_provider_windows: 2.3.0
  permission_handler: ^12.0.0+1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.15
  shared_preferences_foundation: ^2.5.5
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: ^2.4.3
  shared_preferences_windows: 2.4.1
  smooth_page_indicator: ^1.2.1
  # sqflite: ^2.3.3+1
  # sqflite_common: ^2.5.4
  timeago: ^3.7.1
  universal_io: 2.2.2
  url_launcher: ^6.3.2
  url_launcher_android: ^6.3.24
  url_launcher_ios: ^6.3.5
  url_launcher_linux: ^3.2.1
  url_launcher_macos: ^3.2.4
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: ^2.4.1
  url_launcher_windows: ^3.1.4
  xml: ^6.6.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  image: ^4.1.7
  flutter_image_compress: ^2.4.0
  mobile_scanner: ^7.1.4
  # sqflite_android: ^2.3.0+1
  # background_remover: ^0.0.3
  # image_background_remover: ^1.0.0

dependency_overrides:
  # sqflite_android: ^2.3.0+1
  http: 1.2.2
  uuid: ^4.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
  image_path: "assets/images/adaptive_foreground_icon.png"
  adaptive_icon_background: "#081c30"
  adaptive_icon_foreground: "assets/images/adaptive_foreground_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/

  fonts:
    - family: "SF Pro"
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
